stages:
  - build
  - release

before_script:
  - echo $GOPATH
  - ln -s /builds /go/src/github.com
  - cd /go/src/github.com/containernetworking/cni
  - go get ${TOOLS_CMD}/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

variables:
  TOOLS_CMD: "golang.org/x/tools/cmd"
  GO15VENDOREXPERIMENT: "1"
  TARGET: "amd64"
  GOARCH: "amd64"
    
compile:
  image: golang:1.8.1
  stage: build
  script:
    - ./build.sh
    - echo CNI_BINARIES=$CI_PROJECT_URL/builds/$CI_JOB_ID/artifacts/download >> release.env
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 4 weeks
    paths:
      - bin/
      - release.env

release:
  stage: release
  image: golang:1.8.1
  script:
    - cat release.env
  dependencies:
    - compile
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 4 weeks
    paths:
      - release.env
      - bin/
